config = {'tag': None,
          'prefix': 'pool',
          'prep_ver':1, 
          'NCV': 5,
          'margin': 8,
          'imgsp':(1.0, 1.0, 1.0),
          'img_szx': 240,
          'img_szy': 240,
          'img_szz': 155,
          'crop_szx':128,
          'crop_szy':128,
          'crop_szz':128,
          'OARs': {'WT':1, 'TC':2, 'ET': 3}, # WT: whole tumor; TC: tumor core; ET: enhanced tumor
          'img_ch': ['t1','t1ce','t2','flair'], # number of image channels
          'lower_bound': None,
          'upper_bound': None, # Slicer default w/l for abdomen
          'z_transform': None,
          'hq': False, # if voi_histogram_equalization will be applied
          'shift': None,
          'rotate': 0,
          'scale': 0,
          'p_lr': 0.5,
          'p_ud': 0.5,
          'p_si': 0.5,
          'p_rot90':0,
          'pct_norm_tr': None,
          'pct_norm': None,
          'contrast': (0.9,1.1),
          'gamma': None,
          'augument_fcn':'img_augument3d',
          'model': 'sanet1_2_0',
          'up_mode': 'upconv',
          'group_norm': 1,
          'dropout_p' : 0.2,
          'depth': 5,
          'nf': 12,
          'optim': 'adam',
          'loss':'bja_bfl_orl',
          'val_loss':'bja_orl',
          'weight_sample':[0.17, 0.33, 0.50],
          'dp':True,
          'val_ma_alpha':0.9,
          'grad_norm_clip':0.1, # gradient clip
          'pretrained': None,
          'gan':None,
          'tta':False, # test-time augumentation
          'n_warmup': 0,
          }