# inherited from amos22/task1/release/configs/config_v230203 (same as config_v220721-2, YY, 07/23/23

config = {'tag': None,
          'prefix': 'PanSeg',
          'prep_ver':1,
          'NCV': 5,
          'margin': [0, 0, 0],
          'imgsp':(1.0, 1.0, 2.0),
          'img_szx': None,
          'img_szy': None,
          'img_szz': None,
          'crop_szx':160,
          'crop_szy':160,
          'crop_szz':64,
          'OARs': {'pancreas':1},
          'label_mapping': None,
          'exclude_labels': None,
          'class_sampling_prob':None,
          'copy_label': True,
          'img_ch': ['img'],
          'lower_bound': -1000.0,
          'upper_bound': 1000.0,
          'z_transform': [0.0, 1.0],
          'gaussian_noise': {'p': 0.1, 'range': (0, 0.1)},
          'gaussian_blur': {'p': 0.2, 'range': (0.5, 1.0)},
          'bright_mul': {'p': 0.15, 'range': (0.75, 1.25)},
          'shift': None,
          'contrast': {'p': 0.2, 'range':(0.75, 1.25)},
          'gamma_invert': {'p': 0.1, 'range': (0.7, 1.5)},
          'gamma':{'p': 0.3, 'range':(0.7, 1.5)},
          'low_resolution': {'p': 0.25, 'range': (0.5, 1.0)},
          'rotate': {'p':0.2, 'range': (-30,30)},
          'scale': {'p': 0.2, 'range': (0.70, 1.40)},
          'p_lr': 0.2,
          'p_ud': 0.2,
          'p_si': 0.2,
          'model':'sanet1_2_0_v2',
          'augment_fcn': 'train_img_augment3d',
          'up_mode': 'upconv',
          'dropout_p' : 0.0,
          'depth': 6,
          'dp_separate_z':True,
          'nf':12,
          'optim': 'adam',
          'lr_decay': 'step',
          'init':'kaiming',
          'nonlin':'leaky_relu',
          'loss':'gja_ce_new',
          'val_loss':'gja_new',
          'val_with_background':True,
          'valid_start':0,
          'group_norm':1,
          'dp': True,
          'weight_sample': [1,1],
          'val_ma_alpha': 0.9,
          'grad_norm_clip': 0.1,
          'num_training_per_val':1,
          'num_rois_per_case':2,
          'amp': True,
          'val_sliding_window': True,
          'use_gaussian':False,
          'tta': False,
          'pretrained': None,
          'gan': None
          }

